#!/bin/sh
#lang/lars_de.js
cat ../ext2/adapter/ext/ext-base.js ../ext2/ext-all.js lang/ext-lang-de.js ASCIIMathML2wMnGFallback.js ux/TabCloseMenu.js copy.js ux/miframe.js ux/Ext.ux.TinyMCE.js ux/uxmedia.js ux/uxflash.js menu/EditableItem.js menu/RangeMenu.js grid/Ext.ux.grid.RowActions.js grid/Ext.ux.grid.Search.js grid/RowExpander.js grid/Ext.Grid.CheckColumn.js lang/lars_de.js LarsViewer.js LarsUpdater.js LarsOverrides.js LarsBrowseFileWindow.js LarsTreePanelFolderLinks.js LarsTreePanelLinks.js LarsResourcesPanel.js LarsResourcesAddWindow.js LarsResourcesAddNameWindow.js LarsCommentWindow.js LarsDesktopDiscussion.js LarsDesktop.js LarsDesktopNorth3.js LarsDesktopNotes.js LarsDesktopGrid.js LarsNewHtmlTextWindow.js LarsNewHtmlTextWindowNew.js LarsSetPackageRightsWindow.js LarsPackageDiscussion.js LarsHtmlMessageWindow.js LarsCustomImagePanel.js LarsCustomPanelTextChange.js LarsUploadImageWindow.js LarsMessageWindow.js LarsTreePanelDesk.js LarsTreePanelDeskOthers.js LarsPackageGrid.js LarsPackagePanel.js LarsGroupsDesktopsGrid.js LarsGroupsDesktopsGridWindow.js LarsGroupsRightsGrid.js LarsGroupsRightsGridWindow.js LarsGroupsTreePanel.js LarsGroupsTreePanelWindow.js LarsGroupsAddUserWindow.js LarsDocumentsSubscriptionWindow.js LarsDocumentsSubscriptionGrid.js LarsAddFolderWindow.js LarsAddFolderLinksWindow.js LarsAddSchuelerWindow.js LarsAddLinkWindow.js LarsUploadFileWindow.js LarsHtmlPanel.js LarsIFramePanel.js LarsIFramePanelInternet.js LarsAddAssignmentWindow.js LarsMainPanel.js LarsTreePanelArchivWindow.js LarsTreePanelArchiv.js LarsTreePanel.js LarsTreePanelBin.js LarsTreePanelBinWindow.js LarsTopicsPanel.js LarsDesktopErrorWindow.js LarsVoiceChat.js LarsJoinChat.js LarsTopicsPanelTeacher.js LarsChangeDescWindow.js ux/Ext.ux.ToastLars.js ux/Ext.ux.ToastLarsDiscussion.js > LarsSchreibtisch.js
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar LarsSchreibtisch.js -o LarsSchreibtischMin_colloquial.js

#lang/lars_de.js lang/moko_de.js
cat ../ext2/adapter/ext/ext-base.js ../ext2/ext-all.js lang/ext-lang-de.js ASCIIMathML2wMnGFallback.js ux/TabCloseMenu.js copy.js ux/miframe.js ux/Ext.ux.TinyMCE.js ux/uxmedia.js ux/uxflash.js menu/EditableItem.js menu/RangeMenu.js grid/Ext.ux.grid.RowActions.js grid/Ext.ux.grid.Search.js grid/RowExpander.js grid/Ext.Grid.CheckColumn.js lang/lars_de.js lang/moko_de.js LarsViewer.js LarsUpdater.js LarsOverrides.js LarsBrowseFileWindow.js LarsTreePanelFolderLinks.js LarsTreePanelLinks.js LarsResourcesPanel.js LarsResourcesAddWindow.js LarsResourcesAddNameWindow.js LarsCommentWindow.js LarsDesktopDiscussion.js LarsDesktop.js LarsDesktopNorth3.js LarsDesktopNotes.js LarsDesktopGrid.js LarsNewHtmlTextWindow.js LarsNewHtmlTextWindowNew.js LarsSetPackageRightsWindow.js LarsPackageDiscussion.js LarsHtmlMessageWindow.js LarsCustomImagePanel.js LarsCustomPanelTextChange.js LarsUploadImageWindow.js LarsMessageWindow.js LarsTreePanelDesk.js LarsTreePanelDeskOthers.js LarsPackageGrid.js LarsPackagePanel.js LarsGroupsDesktopsGrid.js LarsGroupsDesktopsGridWindow.js LarsGroupsRightsGrid.js LarsGroupsRightsGridWindow.js LarsGroupsTreePanel.js LarsGroupsTreePanelWindow.js LarsGroupsAddUserWindow.js LarsDocumentsSubscriptionWindow.js LarsDocumentsSubscriptionGrid.js LarsAddFolderWindow.js LarsAddFolderLinksWindow.js LarsAddSchuelerWindow.js LarsAddLinkWindow.js LarsUploadFileWindow.js LarsHtmlPanel.js LarsIFramePanel.js LarsIFramePanelInternet.js LarsAddAssignmentWindow.js LarsMainPanel.js LarsTreePanelArchivWindow.js LarsTreePanelArchiv.js LarsTreePanel.js LarsTreePanelBin.js LarsTreePanelBinWindow.js LarsTopicsPanel.js LarsDesktopErrorWindow.js LarsVoiceChat.js LarsJoinChat.js LarsTopicsPanelTeacher.js LarsChangeDescWindow.js ux/Ext.ux.ToastLars.js ux/Ext.ux.ToastLarsDiscussion.js > LarsSchreibtisch.js
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar LarsSchreibtisch.js -o LarsSchreibtischMin_formal.js

#lang/lars_en.js lang/moko_en.js ext-lang-en.js
cat ../ext2/adapter/ext/ext-base.js ../ext2/ext-all.js lang/ext-lang-en.js ASCIIMathML2wMnGFallback.js ux/TabCloseMenu.js copy.js ux/miframe.js ux/Ext.ux.TinyMCE.js ux/uxmedia.js ux/uxflash.js menu/EditableItem.js menu/RangeMenu.js grid/Ext.ux.grid.RowActions.js grid/Ext.ux.grid.Search.js grid/RowExpander.js grid/Ext.Grid.CheckColumn.js lang/lars_en.js lang/moko_en.js LarsViewer.js LarsUpdater.js LarsOverrides.js LarsBrowseFileWindow.js LarsTreePanelFolderLinks.js LarsTreePanelLinks.js LarsResourcesPanel.js LarsResourcesAddWindow.js LarsResourcesAddNameWindow.js LarsCommentWindow.js LarsDesktopDiscussion.js LarsDesktop.js LarsDesktopNorth3.js LarsDesktopNotes.js LarsDesktopGrid.js LarsNewHtmlTextWindow.js LarsNewHtmlTextWindowNew.js LarsSetPackageRightsWindow.js LarsPackageDiscussion.js LarsHtmlMessageWindow.js LarsCustomImagePanel.js LarsCustomPanelTextChange.js LarsUploadImageWindow.js LarsMessageWindow.js LarsTreePanelDesk.js LarsTreePanelDeskOthers.js LarsPackageGrid.js LarsPackagePanel.js LarsGroupsDesktopsGrid.js LarsGroupsDesktopsGridWindow.js LarsGroupsRightsGrid.js LarsGroupsRightsGridWindow.js LarsGroupsTreePanel.js LarsGroupsTreePanelWindow.js LarsGroupsAddUserWindow.js LarsDocumentsSubscriptionWindow.js LarsDocumentsSubscriptionGrid.js LarsAddFolderWindow.js LarsAddFolderLinksWindow.js LarsAddSchuelerWindow.js LarsAddLinkWindow.js LarsUploadFileWindow.js LarsHtmlPanel.js LarsIFramePanel.js LarsIFramePanelInternet.js LarsAddAssignmentWindow.js LarsMainPanel.js LarsTreePanelArchivWindow.js LarsTreePanelArchiv.js LarsTreePanel.js LarsTreePanelBin.js LarsTreePanelBinWindow.js LarsTopicsPanel.js LarsDesktopErrorWindow.js LarsVoiceChat.js LarsJoinChat.js LarsTopicsPanelTeacher.js LarsChangeDescWindow.js ux/Ext.ux.ToastLars.js ux/Ext.ux.ToastLarsDiscussion.js > LarsSchreibtisch.js
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar LarsSchreibtisch.js -o LarsSchreibtischMinEn_formal.js

#lang/lars_en.js ext-lang-en.js
cat ../ext2/adapter/ext/ext-base.js ../ext2/ext-all.js lang/ext-lang-en.js ASCIIMathML2wMnGFallback.js ux/TabCloseMenu.js copy.js ux/miframe.js ux/Ext.ux.TinyMCE.js ux/uxmedia.js ux/uxflash.js menu/EditableItem.js menu/RangeMenu.js grid/Ext.ux.grid.RowActions.js grid/Ext.ux.grid.Search.js grid/RowExpander.js grid/Ext.Grid.CheckColumn.js lang/lars_en.js LarsViewer.js LarsUpdater.js LarsOverrides.js LarsBrowseFileWindow.js LarsTreePanelFolderLinks.js LarsTreePanelLinks.js LarsResourcesPanel.js LarsResourcesAddWindow.js LarsResourcesAddNameWindow.js LarsCommentWindow.js LarsDesktopDiscussion.js LarsDesktop.js LarsDesktopNorth3.js LarsDesktopNotes.js LarsDesktopGrid.js LarsNewHtmlTextWindow.js LarsNewHtmlTextWindowNew.js LarsSetPackageRightsWindow.js LarsPackageDiscussion.js LarsHtmlMessageWindow.js LarsCustomImagePanel.js LarsCustomPanelTextChange.js LarsUploadImageWindow.js LarsMessageWindow.js LarsTreePanelDesk.js LarsTreePanelDeskOthers.js LarsPackageGrid.js LarsPackagePanel.js LarsGroupsDesktopsGrid.js LarsGroupsDesktopsGridWindow.js LarsGroupsRightsGrid.js LarsGroupsRightsGridWindow.js LarsGroupsTreePanel.js LarsGroupsTreePanelWindow.js LarsGroupsAddUserWindow.js LarsDocumentsSubscriptionWindow.js LarsDocumentsSubscriptionGrid.js LarsAddFolderWindow.js LarsAddFolderLinksWindow.js LarsAddSchuelerWindow.js LarsAddLinkWindow.js LarsUploadFileWindow.js LarsHtmlPanel.js LarsIFramePanel.js LarsIFramePanelInternet.js LarsAddAssignmentWindow.js LarsMainPanel.js LarsTreePanelArchivWindow.js LarsTreePanelArchiv.js LarsTreePanel.js LarsTreePanelBin.js LarsTreePanelBinWindow.js LarsTopicsPanel.js LarsDesktopErrorWindow.js LarsVoiceChat.js LarsJoinChat.js LarsTopicsPanelTeacher.js LarsChangeDescWindow.js ux/Ext.ux.ToastLars.js ux/Ext.ux.ToastLarsDiscussion.js > LarsSchreibtisch.js
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar LarsSchreibtisch.js -o LarsSchreibtischMinEn.js

#lang/lars_fr.js ext-lang-fr.js
cat ../ext2/adapter/ext/ext-base.js ../ext2/ext-all.js lang/ext-lang-fr.js ASCIIMathML2wMnGFallback.js ux/TabCloseMenu.js copy.js ux/miframe.js ux/Ext.ux.TinyMCE.js ux/uxmedia.js ux/uxflash.js menu/EditableItem.js menu/RangeMenu.js grid/Ext.ux.grid.RowActions.js grid/Ext.ux.grid.Search.js grid/RowExpander.js grid/Ext.Grid.CheckColumn.js lang/lars_fr.js LarsViewer.js LarsUpdater.js LarsOverrides.js LarsBrowseFileWindow.js LarsTreePanelFolderLinks.js LarsTreePanelLinks.js LarsResourcesPanel.js LarsResourcesAddWindow.js LarsResourcesAddNameWindow.js LarsCommentWindow.js LarsDesktopDiscussion.js LarsDesktop.js LarsDesktopNorth3.js LarsDesktopNotes.js LarsDesktopGrid.js LarsNewHtmlTextWindow.js LarsNewHtmlTextWindowNew.js LarsSetPackageRightsWindow.js LarsPackageDiscussion.js LarsHtmlMessageWindow.js LarsCustomImagePanel.js LarsCustomPanelTextChange.js LarsUploadImageWindow.js LarsMessageWindow.js LarsTreePanelDesk.js LarsTreePanelDeskOthers.js LarsPackageGrid.js LarsPackagePanel.js LarsGroupsDesktopsGrid.js LarsGroupsDesktopsGridWindow.js LarsGroupsRightsGrid.js LarsGroupsRightsGridWindow.js LarsGroupsTreePanel.js LarsGroupsTreePanelWindow.js LarsGroupsAddUserWindow.js LarsDocumentsSubscriptionWindow.js LarsDocumentsSubscriptionGrid.js LarsAddFolderWindow.js LarsAddFolderLinksWindow.js LarsAddSchuelerWindow.js LarsAddLinkWindow.js LarsUploadFileWindow.js LarsHtmlPanel.js LarsIFramePanel.js LarsIFramePanelInternet.js LarsAddAssignmentWindow.js LarsMainPanel.js LarsTreePanelArchivWindow.js LarsTreePanelArchiv.js LarsTreePanel.js LarsTreePanelBin.js LarsTreePanelBinWindow.js LarsTopicsPanel.js LarsDesktopErrorWindow.js LarsVoiceChat.js LarsJoinChat.js LarsTopicsPanelTeacher.js LarsChangeDescWindow.js ux/Ext.ux.ToastLars.js ux/Ext.ux.ToastLarsDiscussion.js > LarsSchreibtisch.js
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar LarsSchreibtisch.js -o LarsSchreibtischMinFr.js


cat css/rowactions.css css/Ext.ux.grid.RowActions.css css/larsDesktop.css css/filetype.css > css/LarsSchreibtischCss.css
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar css/LarsSchreibtischCss.css -o css/LarsSchreibtischCssMin.css
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar ../ext2/resources/css/ext-all.css -o ../ext2/resources/css/ext-allMin.css
#cat tiny_mce/plugins/asciimath/js/ASCIIMathMLwFallback.js tiny_mce/plugins/asciisvg/js/ASCIIsvgPI.js > ../MathPluginsHtml.js
#java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar ../MathPluginsHtml.js -o ../MathPluginsHtmlMin.js
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar tiny_mce/plugins/asciisvg/js/ASCIIsvgPI.js -o tiny_mce/plugins/asciisvg/js/ASCIIsvgPIMin.js
java -jar yuicompressor-2.4.1/build/yuicompressor-2.4.1.jar tiny_mce/plugins/asciimath/js/ASCIIMathMLwFallback.js -o  tiny_mce/plugins/asciimath/js/ASCIIMathMLwFallbackMin.js
